-- TEENAI Supabase schema reference file
-- reference-only. Do NOT run manually. All DB changes go to migrations. CI will apply.
--
-- Schema SQL has been moved to versioned migration files in:
--   supabase/migrations/
--
-- Initial baseline:
--   supabase/migrations/20260218190000_init_schema.sql
--
-- 운영 원칙:
-- 1) schema.sql 직접 실행 금지
-- 2) 모든 변경은 timestamp 기반 migration 파일로 추가
-- 3) main push 후 GitHub Actions에서 supabase db push로 자동 반영
