-- Deprecated: do not execute this file directly.
--
-- Single source of truth:
-- 1) supabase/schema.sql
-- 2) supabase/migrations/*.sql (in filename order)
--
-- Historical statements from this file were moved into:
-- - supabase/migrations/20260220_admin_codes_and_ops_tables.sql
